"""`docker cutover init <image:tag>` - scaffold a new blue/green project."""

import re

from .compose import parse_image_reference
from .nginx import atomic_write, write_upstream

_NAME_RE = re.compile(r"[^a-z0-9_-]+")

NGINX_CONF_TEMPLATE = """worker_processes auto;
error_log /dev/stderr notice;
pid /var/run/nginx.pid;
events {{ worker_connections 1024; }}
http {{
    access_log /dev/stdout;
    resolver 127.0.0.11 valid=5s ipv6=off;
    include /etc/nginx/conf.d/*.conf;
    server {{
        listen {port};
        location / {{
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 2s;
            # Generous on purpose: a short timeout here turns an app that's
            # merely slow to respond into a hard NGINX 502/504 during a
            # deploy's health/verification probes. Tighten it if your app's
            # own latency budget calls for it.
            proxy_read_timeout 130s;
        }}
    }}
}}
"""

COMPOSE_TEMPLATE = """name: {project_name}

x-app: &app
  pull_policy: never
  restart: unless-stopped
  networks: [demo]
  healthcheck:
    # Adjust this to your app's real health endpoint. This assumes wget is
    # available inside the image (true for most Alpine/busybox-based images).
    # No HTTP client in the image? Use a raw TCP probe instead, e.g.:
    #   test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/{port} || exit 1"]
    #
    # `docker cutover <image>:<tag>` additionally requires that same endpoint
    # to return JSON {{"slot": "blue"|"green", "version": "<tag>", "hostname": "..."}}
    # (hostname just needs to be non-empty) - it's how a switch verifies the
    # new slot is really serving the new version before it stops the old one.
    # $SLOT below is already the right value to put in that response.
    # 127.0.0.1, not localhost: many minimal images list ::1 (IPv6) first in
    # /etc/hosts, and wget won't fall back to IPv4 if that connection fails.
    test: ["CMD", "wget", "-q", "-T", "2", "-O", "/dev/null", "http://127.0.0.1:{port}/health"]
    interval: 2s
    timeout: 3s
    retries: 15
    start_period: 2s

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports: ["127.0.0.1:{port}:{port}"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks: [demo]

  app-blue:
    <<: *app
    image: ${{BLUE_IMAGE}}:${{BLUE_VERSION}}
    environment:
      SLOT: blue

  app-green:
    <<: *app
    image: ${{GREEN_IMAGE}}:${{GREEN_VERSION}}
    environment:
      SLOT: green

networks:
  demo:
    driver: bridge
"""

ENV_TEMPLATE = """# Generated by `docker cutover init`. Required by 'docker cutover doctor' /
# 'docker cutover <image>:<tag>' - do not remove.
BLUE_IMAGE={image_name}
BLUE_VERSION={tag}
GREEN_IMAGE={image_name}
GREEN_VERSION={tag}
NGINX_UPSTREAM_CONF=nginx/conf.d/upstream.conf
NGINX_RELOAD_CMD=nginx -s reload

# Optional - shown here with their effective defaults; edit if your setup differs.
NGINX_SERVICE=nginx
NGINX_TEST_CMD=nginx -t
APP_SERVICE_PREFIX=app
APP_PORT={port}
PUBLIC_URL=http://localhost:{port}/health
DRAIN_TIMEOUT=60
"""


def _project_name(root):
    name = _NAME_RE.sub("-", root.name.lower()).strip("-")
    return name or "cutover-project"


def init(root, image_reference, port, force):
    image_name, tag = parse_image_reference(image_reference)

    compose_file = root / "docker-compose.yml"
    env_file = root / ".env"
    nginx_dir = root / "nginx"
    existing = [p.name for p in (compose_file, env_file, nginx_dir) if p.exists()]
    if existing and not force:
        raise RuntimeError(
            f"{', '.join(existing)} already exist in {root}; refusing to overwrite. "
            "Remove them first or pass --force."
        )

    (nginx_dir / "conf.d").mkdir(parents=True, exist_ok=True)
    atomic_write(nginx_dir / "nginx.conf", NGINX_CONF_TEMPLATE.format(port=port))
    write_upstream(nginx_dir / "conf.d" / "upstream.conf", "app", "blue", str(port))
    atomic_write(compose_file, COMPOSE_TEMPLATE.format(project_name=_project_name(root), port=port))
    atomic_write(env_file, ENV_TEMPLATE.format(image_name=image_name, tag=tag, port=port))

    print(f"==> Scaffolded a blue/green project for {image_name}:{tag} in {root}")
    print("    docker-compose.yml, .env, nginx/nginx.conf, nginx/conf.d/upstream.conf")
    print()
    print("Before deploying, your app's /health endpoint (see docker-compose.yml) must:")
    print("  1. respond to the wget-based healthcheck (adjust it if wget isn't in the image)")
    print('  2. return JSON {"slot": "blue"|"green", "version": "<tag>", "hostname": "..."}')
    print("     so a switch can verify the new slot is really serving the new version -")
    print("     $SLOT is already set as an env var on each container for this.")
    print()
    print("Then:")
    print("    docker cutover up")
    print("    docker cutover doctor")
    return 0
